export const productData = [
	{
		id: 1,
		brand: 'sneaker company',
		name: 'Fall Limited edition',
		description: `These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they'll withstand everything the weather can offer.`,
		regularPrice: 125,
		isDiscount: true,
		discountValue: 50,
		imageUrl: '/image-product-1.jpg',
		thumbUrl: '/image-product-1-thumbnail.jpg',
	},
	{
		id: 2,
		brand: 'sneaker company',
		name: 'Summer Breeze',
		description: `Lightweight and breathable, these sneakers are designed for comfort in warm weather. The mesh upper provides excellent airflow for those hot summer days.`,
		regularPrice: 95,
		isDiscount: false,
		discountValue: 0,
		imageUrl: '/image-product-2.jpg',
		thumbUrl: '/image-product-2-thumbnail.jpg',
	},
	{
		id: 3,
		brand: 'sneaker company',
		name: 'Mountain Explorer',
		description: `Built for rugged terrain, these sneakers feature extra grip and durability, perfect for hiking or outdoor adventures. The reinforced toe cap offers added protection.`,
		regularPrice: 140,
		isDiscount: true,
		discountValue: 30,
		imageUrl: '/image-product-3.jpg',
		thumbUrl: '/image-product-3-thumbnail.jpg',
	},
	{
		id: 4,
		brand: 'sneaker company',
		name: 'Urban Nights',
		description: `Sleek and stylish, these all-black sneakers are designed for a modern, minimalist look. The reflective detailing adds a subtle flair for evening wear.`,
		regularPrice: 110,
		isDiscount: false,
		discountValue: 0,
		imageUrl: '/image-product-4.jpg',
		thumbUrl: '/image-product-4-thumbnail.jpg',
	},
];
